CLEAN_FIND_FILES := *.txt out.rst* *.restart *.state *.log mdout.mdp EXIT *.tpr
CLEAN_RM_PATHS := run-initialise/0* run-5/0* run-load/0* run-load/initial_path gromacs_input/pyretis.mdp

include $(shell git rev-parse --show-toplevel)/examples/test/common-clean.mk
