travis:
  secure:
    BINSTAR_TOKEN: Qdbzb88CTuUK5HQumhsS7ac50jYiQFPQAcmWm9AVIvaMJfW8TAKpa/ZpjlISnETVmu/uE6VfeQSRUNU3qrj2Xyi1xg2RnCrR6a6p1HiseYbmPg3BWgtk84poJBF1eKNagEcaxWoVqdqgWz7bqde+3hoYdBa9xe3OYdhwLYVI4reg9PTOalCZRmsc7Bb3XNtlteov93Sr0QtXzjX+F5IxqrIc/FPnMuvxcXAGmzwN0EPm90OCROaSTTyelwxxyfUWQQSdyrHFiR3OEh3ZozmUN3EMSc1qZIlC4TyooCecUj9W7Y9cdC5SpyRfSeN3oZy+ty3qrpjkkeT1CLXwxFg4l5slCs9pWciv5k1ReGT+y1mpGyh86qccDXuT1XD01tVlOD9D9s+F66NsOh6zK3r2InoPO7We1CPKauPvp4r+1j6t70hvImqjx2y4QiWWAAegNdVkKdtbxoLL1fXZ4pShiUDO4cYs4cCZnpQ2rVeo0pn9G2Kv5MN6o8uiRjfhnFVrigY8BO53QREdQewUrgXJyLHHkhQAngrq8PGVsUuvDLmMN4JOOARBaDWTyAJyf6vHETFrz0TsFG7DD93ukp7I/88Zo2DYd/IacLPsKrQNfgFyRQt5aDF4zhhXUoepmoThC5iaLs46dR5hxKYrYPsnB4jnEo+HAbMmqvu/haYl/e8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
