CLEAN_FIND_FILES := *.txt *.wfn *out.rst* *.restart *log* *.bak-*
CLEAN_RM_PATHS := 0* *pyretis-cp2k* step.inp continue.inp conf.xyz cp2k_input/pyretis.inp cp2k-run

include $(shell git rev-parse --show-toplevel)/examples/test/common-clean.mk
