CLEAN_FIND_FILES := *.txt out.rst* *.restart rnd.state *.log mdout.mdp pyretis.mdp EXIT *.tpr
CLEAN_RM_PATHS := 0-forward-step 0-backward-step 0-backward-plain 0-forward-plain 1-forward-step 1-backward-step 1-backward-plain 1-forward-plain 2-forward-step 2-backward-step 2-backward-plain 2-forward-plain engine-run.rst

include $(shell git rev-parse --show-toplevel)/examples/test/common-clean.mk
