CLEAN_FIND_FILES := EXIT *.txt out.rst* *.restart *.state *.log* mdout.mdp *.tpr
CLEAN_RM_PATHS := run-5/0* run-10/0* run-restart/0* gromacs_input/conf.gro gromacs_input/pyretis.mdp

include $(shell git rev-parse --show-toplevel)/examples/test/common-clean.mk
