# Copyright (c) 2026, PyRETIS Development Team.
# Distributed under the LGPLv2.1+ License. See LICENSE for more info.
"""Version information for PyRETIS.

This file is generated by PyRETIS (``setup_version.py``)
"""
SHORT_VERSION = '3.0.5'
VERSION = '3.0.5'  # pylint: disable=invalid-name
FULL_VERSION = '3.0.5'
GIT_REVISION = 'feafb5133d5c497fbd388b97122294aa8938646c'
GIT_VERSION = '3.0.5'
RELEASE = True

if not RELEASE:
    VERSION = GIT_VERSION  # pylint: disable=invalid-name

MIN_PYTHON_VERSION = (3, 9)
