# -*- coding: utf-8 -*-
# Copyright (c) 2026, PyRETIS Development Team.
# Distributed under the LGPLv2.1+ License. See LICENSE for more info.
"""Version information for PyRETIS.

This file is generated by PyRETIS (``setup_version.py``)
"""
SHORT_VERSION = '3.0.1'
VERSION = '3.0.1'  # pylint: disable=invalid-name
FULL_VERSION = '3.0.1'
GIT_REVISION = 'f9ae02f1d8098f39aede23c4a8017e48b6040e28'
GIT_VERSION = '3.0.1'
RELEASE = True

if not RELEASE:
    VERSION = GIT_VERSION  # pylint: disable=invalid-name

MIN_PYTHON_VERSION = (3, 9)
