CLEAN_FIND_FILES := *.wfn *out.rst* *.restart *.log *.bak-*
CLEAN_RM_PATHS := pippo/*txt pippo/0* report EXIT 0* cp2k_input/pyretis.inp

include $(shell git rev-parse --show-toplevel)/examples/test/common-clean.mk
