CLEAN_FIND_FILES := EXIT *.txt out.rst* *.restart rnd.state *.log mdout.mdp *.tpr pyretis.log*
CLEAN_RM_PATHS := gromacs1/0* gromacs2/0* gromacs_input/pyretis.mdp

include $(shell git rev-parse --show-toplevel)/examples/test/common-clean.mk
