CLEAN_FIND_FILES := EXIT *.txt *out.rst* *.restart *.log* *.xvg* *.edr* *.cpt* *.xtc* *.trr* *mdout.mdp* *pyretis.mdp* *.tpr*
CLEAN_RM_PATHS := gromacs-run.rst conf.g96 *pyretis-gmx* *gromacs-run*

include $(shell git rev-parse --show-toplevel)/examples/test/common-clean.mk
