CLEAN_FIND_FILES := *.txt out.rst* *.restart rnd.state *.log* mdout.mdp EXIT *.tpr
CLEAN_RM_PATHS := run-gromacs*/gromacs_inp* run-gromacs*/retis-run.rst run-gromacs*/0* run-gromacs*/out* gromacs_input/pyretis.mdp

include $(shell git rev-parse --show-toplevel)/examples/test/common-clean.mk
