CLEAN_FIND_FILES := EXIT *.txt out.rst* *.restart rnd.state *.log mdout.mdp *.tpr
CLEAN_RM_PATHS := 0* pippo/0* gromacs_input/pyretis.mdp

include $(shell git rev-parse --show-toplevel)/examples/test/common-clean.mk
