CLEAN_FIND_FILES := EXIT *.txt out.rst* *.restart *.state *.log* mdout.mdp *.tpr
CLEAN_RM_PATHS := run-2/0* run-10/0* run-load/0* run-load/initial_path merged gromacs_input/pyretis.mdp

include $(shell git rev-parse --show-toplevel)/examples/test/common-clean.mk
