CLEAN_FIND_FILES := EXIT *.txt out.rst* *.restart *.state *.log mdout.mdp *.tpr
CLEAN_RM_PATHS := run-initialise/0* run-5/0* run-restart/0* gromacs_input/pyretis.mdp gromacs_input/conf.gro

include $(shell git rev-parse --show-toplevel)/examples/test/common-clean.mk
