CLEAN_FIND_FILES := *.txt out.rs* *.restart *.log*
CLEAN_RM_PATHS := run-10/001 run-10-20/001 run-full/001 run-full/report

include $(shell git rev-parse --show-toplevel)/examples/test/common-clean.mk
