CLEAN_FIND_FILES := *.txt out.rst* *.restart *.log*
CLEAN_RM_PATHS := retis-10/0* retis-10-20/0* retis-10-20/restart retis-full/0*

include $(shell git rev-parse --show-toplevel)/examples/test/common-clean.mk
