CLEAN_FIND_FILES := EXIT out.rst* *.restart rnd.state *.log mdout.mdp *.tpr pyretis.log*
CLEAN_RM_PATHS := pippo/0* pippo/*txt 0*

include $(shell git rev-parse --show-toplevel)/examples/test/common-clean.mk
