CLEAN_FIND_FILES := EXIT *.txt out.rst* *.restart rnd.state *.log mdout.mdp *.tpr
CLEAN_RM_PATHS := results/pyvisa_compressed_data.hdf5 pyvisa_compressed_data* 0* retis-load-rc-run.rst pippo/0* gromacs_input/pyretis.mdp

include $(shell git rev-parse --show-toplevel)/examples/test/common-clean.mk
