CLEAN_FIND_FILES := *.txt *.wfn *out.rst* *.restart *.log *.bak-*
CLEAN_RM_PATHS := 0* cp2k_input/pyretis.inp backward backward-plain forward forward-plain genvel forward-single-step

include $(shell git rev-parse --show-toplevel)/examples/test/common-clean.mk
